### ISSUE TITLE
what is cp？ /cp/resolve/main/tf_model.h5

### ISSUE THREAD

**Issue by yds3** [GengzeZhou/NavGPT-2#4]
OSError: cp is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo either by logging in with `huggingface-cli login` or by passing `token=<your_token>`

**Comment by GengzeZhou** [comment]
Thank you for reaching out. Could you please provide more details on how this issue was triggered? To clarify, we are not downloading any models from a private repository.
